/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.awt.Image;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author diego
 */
public class Inicio extends javax.swing.JFrame {

    int tipo;
    
    public Inicio(int tipo) {
        initComponents();
        this.tipo=tipo;
        iniciador();
        setLocationRelativeTo(null);
    }
    
    public void iniciador(){
        actualizaIconos(imagen,320,185);
        switch(tipo){
            case 1:
            {
                tipoMenu.setText("Sistemas de ecuaciones no lineales");
                boton1.setText("Punto Fijo");
                boton2.setText("Newton - Raphson");
                boton3.setVisible(false);
                break;
            }
            case 2:
            {
                tipoMenu.setText("Interpolación y aproximación polinomial");
                boton1.setText("Interpolación de Newton");
                boton2.setVisible(false);
                boton3.setVisible(false);
                break;
            }
            case 3:
            {
                tipoMenu.setText("Derivación e Integración númerica");
                boton1.setText("Regla Trapezoidal");
                boton2.setText("Regla de Simpson 1/3");
                boton3.setText("Regla de Simpson 3/8");
                break;
            }
        }
    }
    
    private void actualizaIconos(JLabel icono,int ancho,int alto){
        ImageIcon imagen =null;
        switch (tipo){
            case 1:
            {
                imagen = new ImageIcon(getClass().getResource("/imagenes/unidad1.png"));
                try {
                caja.read((new InputStreamReader(getClass().getResourceAsStream("/teoria/1_Introduccion.txt"), "UTF-8")),null);
            } catch (IOException ex) {
                Logger.getLogger(Ejecutor.class.getName()).log(Level.SEVERE, null, ex);
            }
                break;
            }
            case 2:
            {
                imagen = new ImageIcon(getClass().getResource("/imagenes/unidad2.png"));
                try {
                caja.read((new InputStreamReader(getClass().getResourceAsStream("/teoria/2_Introduccion.txt"), "UTF-8")),null);
            } catch (IOException ex) {
                Logger.getLogger(Ejecutor.class.getName()).log(Level.SEVERE, null, ex);
            }
                break;
            }
            case 3:
            {
                imagen = new ImageIcon(getClass().getResource("/imagenes/unidad3.png"));
                try {
                caja.read((new InputStreamReader(getClass().getResourceAsStream("/teoria/3_Introduccion.txt"), "UTF-8")),null);
            } catch (IOException ex) {
                Logger.getLogger(Ejecutor.class.getName()).log(Level.SEVERE, null, ex);
            }
                break;
            }
        }
        icono.setIcon(new ImageIcon(imagen.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imagen = new javax.swing.JLabel();
        tipoMenu = new javax.swing.JLabel();
        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        caja = new javax.swing.JTextPane();
        botonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        imagen.setText("Imagen");

        tipoMenu.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        tipoMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tipoMenu.setText("Tipo menu");

        boton1.setText("Menu1");
        boton1.setActionCommand("");
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });

        boton2.setText("Menu2");
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });

        boton3.setText("Menu3");
        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(caja);

        botonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volver.png"))); // NOI18N
        botonVolver.setText("volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(boton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(boton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                        .addComponent(boton3, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)))
                                .addGap(43, 43, 43)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(323, 323, 323)
                                .addComponent(botonVolver)))
                        .addGap(0, 33, Short.MAX_VALUE))
                    .addComponent(tipoMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(tipoMenu)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(botonVolver)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        Ejecutor ven = null;
        
        switch(tipo){
            case 1:
            {
                ven = new Ejecutor(1);
                break;
            }
            case 2:
            {
                ven = new Ejecutor(3);
                break;
            }
            case 3:
            {
                ven = new Ejecutor(4);
                break;
            }
        }
        ven.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton1ActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        Menu2 ventana = new Menu2();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
        Ejecutor ven = null;
        
        switch(tipo){
            case 1:
            {
                ven = new Ejecutor(2);
                break;
            }
            case 2:
            {
                
                break;
            }
            case 3:
            {
                ven = new Ejecutor(5);
                break;
            }
        }
        ven.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton2ActionPerformed

    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed
        Ejecutor ven = null;
        
        switch(tipo){
            case 1:
            {
                break;
            }
            case 2:
            {
                break;
            }
            case 3:
            {
                ven = new Ejecutor(6);
                break;
            }
        }
        ven.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton3ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton botonVolver;
    private javax.swing.JTextPane caja;
    private javax.swing.JLabel imagen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel tipoMenu;
    // End of variables declaration//GEN-END:variables
}
